import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { SECTION_LABELS, type SectionType } from "@/lib/constants";
import type { ComputedScores } from "@/lib/scoring";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica", color: "#1a1a1a" },
  title: { fontSize: 22, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#555", marginBottom: 16 },
  h2: { fontSize: 14, fontWeight: 700, marginTop: 18, marginBottom: 8, borderBottom: "1pt solid #ddd", paddingBottom: 4 },
  scoreRow: { flexDirection: "row", marginBottom: 12, gap: 8 },
  scoreBox: { flex: 1, border: "1pt solid #e2e2e2", borderRadius: 4, padding: 8 },
  scoreValue: { fontSize: 18, fontWeight: 700 },
  scoreLabel: { fontSize: 8, color: "#666", marginTop: 2 },
  line: { marginBottom: 3, lineHeight: 1.4 },
  bullet: { marginBottom: 3, lineHeight: 1.4 },
  meta: { fontSize: 8, color: "#888", marginTop: 6 },
  footer: { position: "absolute", bottom: 20, left: 36, right: 36, fontSize: 8, color: "#aaa", textAlign: "center" },
});

export interface PdfSection {
  type: SectionType;
  content: unknown;
  source: string;
  confidenceScore: number | null;
}

export interface PdfProjectData {
  name: string;
  industry: string;
  country: string;
  currency: string;
  generatedAt: string;
  scores: ComputedScores | null;
  sections: PdfSection[];
  competitors: { name: string; description: string | null; marketSharePct: number | null }[];
}

function flattenToLines(value: unknown, depth = 0): string[] {
  const indent = "  ".repeat(depth);
  if (value === null || value === undefined) return [];
  if (typeof value === "string" || typeof value === "number") {
    return [`${indent}${value}`];
  }
  if (Array.isArray(value)) {
    return value.flatMap((item) => {
      if (typeof item === "object" && item !== null) {
        return flattenToLines(item, depth);
      }
      return [`${indent}• ${item}`];
    });
  }
  if (typeof value === "object") {
    return Object.entries(value as Record<string, unknown>).flatMap(([key, v]) => {
      const label = key.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase());
      if (typeof v === "object" && v !== null) {
        return [`${indent}${label}:`, ...flattenToLines(v, depth + 1)];
      }
      return [`${indent}${label}: ${v}`];
    });
  }
  return [];
}

function ScoreBox({ label, value }: { label: string; value: number }) {
  return (
    <View style={styles.scoreBox}>
      <Text style={styles.scoreValue}>{value}</Text>
      <Text style={styles.scoreLabel}>{label}</Text>
    </View>
  );
}

function ReportDocument({ data }: { data: PdfProjectData }) {
  return (
    <Document title={`${data.name} — Market Research Report`}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{data.name}</Text>
        <Text style={styles.subtitle}>
          {data.industry} · {data.country} · Generated {data.generatedAt}
        </Text>

        {data.scores && (
          <>
            <View style={styles.scoreRow}>
              <ScoreBox label="Overall Score" value={data.scores.overall} />
              <ScoreBox label="Opportunity" value={data.scores.opportunity} />
              <ScoreBox label="Risk" value={data.scores.risk} />
            </View>
            <View style={styles.scoreRow}>
              <ScoreBox label="Competition" value={data.scores.competition} />
              <ScoreBox label="Demand" value={data.scores.demand} />
              <ScoreBox label="Profitability" value={data.scores.profitability} />
            </View>
            <Text style={styles.line}>Recommendation: {data.scores.investmentRecommendation}</Text>
          </>
        )}

        {data.competitors.length > 0 && (
          <>
            <Text style={styles.h2}>Competitors</Text>
            {data.competitors.map((c, i) => (
              <Text key={i} style={styles.bullet}>
                • {c.name}
                {c.marketSharePct != null ? ` (${c.marketSharePct}% share)` : ""}
                {c.description ? ` — ${c.description}` : ""}
              </Text>
            ))}
          </>
        )}

        {data.sections.map((section) => (
          <View key={section.type}>
            <Text style={styles.h2}>{SECTION_LABELS[section.type]}</Text>
            {flattenToLines(section.content).map((line, i) => (
              <Text key={i} style={styles.line}>
                {line}
              </Text>
            ))}
            <Text style={styles.meta}>
              Source: {section.source}
              {section.confidenceScore != null ? ` · Confidence: ${section.confidenceScore}%` : ""}
            </Text>
          </View>
        ))}

        <Text style={styles.footer} fixed>
          Generated by the Market Research Platform — for informational purposes only.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderProjectPdf(data: PdfProjectData): Promise<Buffer> {
  return renderToBuffer(<ReportDocument data={data} />);
}
